name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_html002
      id: test_html002
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 8
        setup-command: pip install pytest bs4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_HTML002_RESULTS: "${{steps.test_html002.outputs.result}}"
      with:
        runners: test_html002
